import PDFDocument from 'pdfkit';

const fetchImageBuffer = async (url) => {
  if (!url) {
    return null;
  }

  try {
    const response = await fetch(url);
    if (!response.ok) {
      return null;
    }
    const arrayBuffer = await response.arrayBuffer();
    return Buffer.from(arrayBuffer);
  } catch {
    return null;
  }
};

export const generateReceipt = async (transaction, tenant, member) => {
  const doc = new PDFDocument({ margin: 50 });
  const buffers = [];
  const churchLogo = await fetchImageBuffer(tenant?.logoUrl);

  return await new Promise((resolve, reject) => {
    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    if (churchLogo) {
      try {
        doc.image(churchLogo, 50, 40, { width: 55, height: 55 });
      } catch {
        // Ignore invalid logo formats and continue rendering the receipt.
      }
    }

    doc
      .fontSize(20)
      .fillColor('#1E2A4A')
      .text(tenant?.churchName || 'Prynova Church', 120, 45)
      .fontSize(10)
      .fillColor('#6B7280')
      .text(tenant?.email || '', 120, 70)
      .text(tenant?.phone || '', 120, 84);

    doc
      .fontSize(18)
      .fillColor('#C9A84C')
      .text('OFFICIAL RECEIPT', 50, 120, { align: 'right' });

    doc.moveTo(50, 150).lineTo(545, 150).strokeColor('#E5E7EB').stroke();

    const memberName =
      transaction.memberName ||
      member?.fullName ||
      [member?.firstName, member?.lastName].filter(Boolean).join(' ') ||
      'Anonymous Giver';

    const rows = [
      ['Receipt #', transaction.receiptNumber || 'Pending'],
      ['Transaction ID', transaction.transactionId || 'Pending'],
      ['Date', new Date(transaction.serviceDate || transaction.recordedDate).toLocaleDateString()],
      ['Member', memberName],
      ['Type', String(transaction.type || '').replaceAll('_', ' ')],
      ['Amount', `${transaction.currency || 'USD'} ${Number(transaction.amount || 0).toLocaleString()}`],
      ['Payment Method', String(transaction.paymentMethod || 'cash').replaceAll('_', ' ')],
      ['Reference', transaction.paymentReference || 'N/A'],
    ];

    let currentY = 175;
    rows.forEach(([label, value]) => {
      doc
        .fontSize(10)
        .fillColor('#6B7280')
        .text(label, 50, currentY)
        .fontSize(12)
        .fillColor('#111827')
        .text(value, 220, currentY);
      currentY += 24;
    });

    doc
      .roundedRect(50, currentY + 10, 495, 70, 12)
      .fillAndStroke('#F8F7F4', '#E5E7EB')
      .fillColor('#1E2A4A')
      .fontSize(12)
      .text('Thank you for your faithful giving', 70, currentY + 28)
      .fontSize(10)
      .fillColor('#6B7280')
      .text(
        `${tenant?.churchName || 'Your church'} appreciates your generosity and support.`,
        70,
        currentY + 48,
      );

    doc
      .fontSize(9)
      .fillColor('#6B7280')
      .text(
        'Generated by Prynova Finance & Accounting Module',
        50,
        740,
        { align: 'center', width: 495 },
      );

    doc.end();
  });
};

export default generateReceipt;
